### ISSUE TITLE
Console error - undefined function

### ISSUE THREAD

**Issue by tskweres** [mareczek/international-phone-number#1]
Hey Mareczek, 

Nice work on this! Do you happen to have a working example implemented in html/css/js you could post?

I followed the instructions:
- bower installed
- dependency added

And I'm getting the following error in the console:

TypeError: undefined is not a function
    at link (http://192.168.0.3:8100/js/services/international-phone-number.js:44:17)

This is the function in question:

element.intlTelInput(options);
        if (!options.utilsScript) {
          element.intlTelInput('loadUtils', 'bower_components/intl-tel-input/lib/libphonenumber/build/utils.js');
        }

**Comment by ackuser** [comment]
I was having the same issue and I can confirm that putting jquery before than all angularjs libraries can solve the problem. About the transfer data I am completely agree, it may have to be rebuilt with angular.

Thx for comment this issue
