### ISSUE TITLE
When nationalMode is true, store selected country in ng-model value

### ISSUE THREAD

**Issue by 3dd13** [mareczek/international-phone-number#10]

**Comment by 3dd13** [comment]
attempt to store the selected country object in the model value:
https://github.com/3dd13/international-phone-number/commit/eee92cd7aa005ea6baf29dedc4519c198871ea30

however, the model format will be different based on the nationalMode.
any suggestion how to expose the selected country without too many variations of model format ?

**Comment by LiamK** [comment]
Did you come up with anything?  I need to get the nationalMode thing to work, even if it just adds the country code to the number.

**Comment by 3dd13** [comment]
In the commit, I added the country code as part of the result value

so if nationalMode is true, the model will be updated to
{
  countryCode: countryCodeSelected
  phoneNumber: value
}

**Comment by LiamK** [comment]
Thanks... I set bower.json dependency to that commit.
I got the correct coffeescript, but the files in releases dir don't seem
to have been compiled from the coffeescript.
Can you help?

On 03/17/2015 09:05 PM, 3dd13 wrote:
>
> In the commit, I added the country code as part of the result value
>
> so if nationalMode is true, the model will be updated to
> {
> countryCode: countryCodeSelected
> phoneNumber: value
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mareczek/international-phone-number/issues/10#issuecomment-82730171>.
>

-- 
Liam Kirsher
PGP: http://liam.numenet.com/pgp/

**Comment by 3dd13** [comment]
you will need to compile the coffeescript into js
have you done that before ? you can use the following npm package:
https://www.npmjs.com/package/coffee-script

**Comment by LiamK** [comment]
I installed coffee and compiled the file.  However, this is really not the best solution since this is being automatically deployed, and adding a coffee compilation adds another step that I have to program into the deployment.  It's okay, I can just fork international-phone-number myself, and then I only have to run coffee compile once.

I have another question, but I'll create another thread for it.

Thanks for you help.

**Comment by 3dd13** [comment]
usually when you write your own program / tools, you can use Grunt or Gulp
script to manage the build and dist process.
so that you can have a compile task whenever you build and release the
script
this github project does not have that

2015-03-19 10:48 GMT+08:00 Liam K <notifications@github.com>:

**Comment by mareczek** [comment]
Hi guys!
The automatic compilation of coffee to js has been already handled.
As for the nationalMode - passing the country code in the value ... I'm not sure if changing this behaviour is the best solution. I would love to read a bit more opinions.

**Comment by 3dd13** [comment]
right, it is currently a hack to make it work

I suggest standardizing the value to contains both countryCode and phoneNumber regardless nationalMode or not
