### ISSUE TITLE
utils.js is not found on production

### ISSUE THREAD

**Issue by artmees** [mareczek/international-phone-number#19]
I noticed this error `(http://localhost:9000/bower_components/intl-tel-input/lib/libphonenumber/build/utils.js 404 (Not Found))` on production only...

**Comment by artmees** [comment]
this seems to be the problematic line causing the issue on production (where bower_components is packaged into 1 vendor file)

https://github.com/mareczek/international-phone-number/blob/master/src/international-phone-number.coffee#L60

**Comment by artmees** [comment]
I've made a fork here https://github.com/tameny/international-phone-number only removing that line of code and updating the version of intl-tel-input feel free to merge this if you want

**Comment by mareczek** [comment]
This has been fixed, let me know you still have a problem with this
