### ISSUE TITLE
Shows class "ng-invalid" when number is valid

### ISSUE THREAD

**Issue by mpiasta-ca** [mareczek/international-phone-number#2]
Tracked down bug where field would have red outline (due to class of ng-invalid), even thought the phone number was a valid international number. I tried a whole bunch of things, not sure what I ended up changing, but this works:

```
        //pass field value to model
        ngModel.$parsers.push(function (value) {
          if (value) {
            ngModel.$setValidity('invalidIntlTel', element.intlTelInput("isValidNumber"));
          } else {
            //ignore tel validation when field is blank
            ngModel.$setValidity('invalidIntlTel', true);
          }
          return value ? value.replace(/[^\d]/g, '') : '';
        });
```

To reproduce the bug: click the form field to start typing a number, but instead of typing, erase the area code. Blur cursor out of the field, then focus the field again, this time type a valid number. When you blur, the class will be "ng-invalid" even though your number is valid.

**Comment by mareczek** [comment]
@mpiasta-ca let me know if you still have this problem in version (0.0.6). Meanwhile I'm closing this issue.
