### ISSUE TITLE
Directive should be delayed so that it doesn't run _setInitialState before the DOM has been loaded

### ISSUE THREAD

**Issue by Aleksion** [mareczek/international-phone-number#21]
The directive was loading before the value of the input field was populated by the data I provided it. I believe this to be a problem when running the directive in an ng-repeat

it can easilly be fixed by wrapping the directive in a 0ms $timeout - which will queue the loading until after the DOM has finished rendering.

I have limited experience with making pull requests - is this something you can take a look at?

Thank you in advance!

**Comment by facultymatt** [comment]
I believe this has actually been fixed in https://github.com/mareczek/international-phone-number/pull/12 but is not released because of https://github.com/mareczek/international-phone-number/issues/30

**Comment by mareczek** [comment]
Fixed & released
Thanks

**Comment by Aleksion** [comment]
Great! Thanks a lot :+1:
