### ISSUE TITLE
options.utilsScript always attempts to load file even when overwrite attribute was set

### ISSUE THREAD

**Issue by mpiasta-ca** [mareczek/international-phone-number#3]
When I set an attribute `utilsScript="test/fake/path.js"` on my phone form field, the script still attempts to load the the `bower_components/.../utils.js` script. In my app, I load the utils.js manually in the head of my index.html, so I had to remove this piece entirely to make everything  kosher.

```
  element.intlTelInput(options);
  if (!options.utilsScript) {
    element.intlTelInput('loadUtils', 'bower_components/intl-tel-input/lib/libphonenumber/build/utils.js');
  }
```

The way this is coded is very undesirable. Most people will not be using the default `bower_components` folder, so you are making big assumption in your code here. I would not want my directive loading a *.js file. But additionally, int-tel-input already handles this scenario, so you don't have to cover it in the directive.

**Comment by monkeymonk** [comment]
+1 for using `util-scripts="path/to/file"` instead of a default lazy load !
Which is very very ...very bad ! :-)

**Comment by mareczek** [comment]
This has been fixed thanks to @Sjors
