### ISSUE TITLE
wrong directive dependencies in releases/international-phone-number.min.js

### ISSUE THREAD

**Issue by ostapnagovicin** [mareczek/international-phone-number#35]
'internationalPhoneNumber' directive declaration not wrapped in array.  It causes renaming of dependencies (a instead of $timeout) in minified version
```javascript
... .directive("internationalPhoneNumber",function(a) {...
```

**Comment by SelrahcD** [comment]
Yup. It's really an issue for me too.

**Comment by SelrahcD** [comment]
@ostapnagovicin I can make a PR if needed :)

**Comment by mareczek** [comment]
Sure, please do. Thanks

**Comment by SelrahcD** [comment]
Hi !
Thanks for your answer.
PR #40, if ok for you, should fixe the issue.
If not I can create a new one with only the array notation for minification.
