### ISSUE TITLE
Suggestions for int-tel-input calls to integrate

### ISSUE THREAD

**Issue by mpiasta-ca** [mareczek/international-phone-number#4]
When passing a default/init value to the phone form field, it will not have the right masking. In my app, I've expanded `international-phone-number` with this bit of code to apply the int-tel-input masking:

```
  //after directive init, apply masking to default data in tel field
  $timeout(function () {
    if (element.val()) {
      element.intlTelInput("setNumber", element.val());
      scope.$apply(read);
    }
  });
```

And on destroy, you can also destroy the intlTelInput() instance:

```
  element.on('$destroy', function () {
    element.intlTelInput('destroy');
    element.off('blur keyup change');
  });
```

**Comment by ACDN** [comment]
Thanks for you post.. this really helped me get this directive working nicely.
