### ISSUE TITLE
Form is marked as invalid on page load

### ISSUE THREAD

**Issue by jasonhjohnson** [mareczek/international-phone-number#43]
Hi,

When our form first loads it's marked as invalid. If I click inside of our international-phone-number input field the form is magically marked valid. All other validation between the input field itself and it's containing form seem to work.

Any ideas?

Thanks,
Jason

**Comment by ravitejadeevi** [comment]
I am also facing the same problem ( described by @jasonhjohnson ).

**Comment by ghodrat2014** [comment]
check this, it may help you:
https://github.com/mareczek/international-phone-number/issues/39#issuecomment-109266195

**Comment by mareczek** [comment]
Please take a look at version 0.0.9
