### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by Ventajou** [mareczek/international-phone-number#48]
Could you please add a LICENSE file to clarify things? Thanks!

**Comment by mareczek** [comment]
Sure, what would you like to clarify?

**Comment by Roundaround** [comment]
Perhaps if you consider this project to be un-licensed, at least add a notice to the README or a skeleton LICENSE file explaining as such, or maybe even just re-release this under the same MIT license that the jQuery plugin is under.  Would make things much simpler to reference back when it's used in production environments.  :)

**Comment by mareczek** [comment]
Done
