### ISSUE TITLE
Releases files are not mangled !

### ISSUE THREAD

**Issue by monkeymonk** [mareczek/international-phone-number#54]
The code compiled from CoffeeScript lose the mangled dependencies.

Currently:
```javascript
.directive('internationalPhoneNumber', function($timeout) {
```

Should be:
```javascript
.directive('internationalPhoneNumber', ['$timeout', function($timeout) {
```

This should be mandatory.

**Comment by pra85** [comment]
The .coffee file is mangled now after #42 got merged but grunt hasn't been run therefore the release folders files are still old

**Comment by monkeymonk** [comment]
Ok ! This is the same version used in `bower` so that will be cool to release update mangled and update the `bower` ! ;-)

**Comment by mareczek** [comment]
@pra85 just released your pull reques, thanks
