### ISSUE TITLE
Publishing on npm

### ISSUE THREAD

**Issue by mkolodny** [mareczek/international-phone-number#59]
Thanks for the package! Please [publish it on npm](https://docs.npmjs.com/getting-started/publishing-npm-packages) so that people who use CommonJS/[Browserify](https://github.com/substack/node-browserify) can install it with `npm install international-phone-number`.

**Comment by mareczek** [comment]
Done, https://www.npmjs.com/package/international-phone-number
Although I could use some help because the version number shown on npmjs is 0.0.1 and today i released 0.0.9

**Comment by skfd** [comment]
Looks like you need to update version in `package.json`. Sorry for reopening.
