### ISSUE TITLE
Can I dynamically change selected country?

### ISSUE THREAD

**Issue by skfd** [mareczek/international-phone-number#60]
I have a separate control for country so I want to one way bind selected country or just call `selectCountry` method.

Can this library do this?

**Comment by skfd** [comment]
I've exposed `country` in scope. And made simple watch expression:

          scope.$watch('country', function(newValue) {
              if (newValue !== null && newValue !== void 0 && newValue !== '') {
                element.intlTelInput("selectCountry", newValue);
              }
          });

Should I make pull request? I think it's useful and untaxing feature...

**Comment by mareczek** [comment]
@skfd please do, looks like a legit feature!

**Comment by skfd** [comment]
Made a pull request

**Comment by mareczek** [comment]
Merged and release `0.0.15`
