### ISSUE TITLE
Bare dial code is treated as valid number.

### ISSUE THREAD

**Issue by skfd** [mareczek/international-phone-number#61]
Shouldn't phone number `+1` be invalid even if it is not required? Bare dial code is just garbage.

**Comment by mareczek** [comment]
No, the '+1' alone is not written to model value. If you wan't to validate presence of a phone number just add ng-required

**Comment by lgoudriaan** [comment]
'1' will be writen to the model value when you set national-mode to false. See http://plnkr.co/edit/pPXjv1alPNgvdBSMyS0w?p=preview
