### ISSUE TITLE
No way to globally customize default options

### ISSUE THREAD

**Issue by angrybakon** [mareczek/international-phone-number#62]
We should have an `options` attribute in order to customize default options, which then can be overwritten by other attributes.

Priorities:

1. Other attributes
1. `options` attribute
1. Default options (set in [`international-phone-number.js:32`][hardcoded-options])

[hardcoded-options]: https://github.com/mareczek/international-phone-number/blob/master/releases/international-phone-number.js#L32

**Comment by exiadbq** [comment]
My 2 cents opinion, It can be done by using a external json, guess jquery must be loaded for this. 
http://stackoverflow.com/questions/22825706/angularjs-load-config-on-app-start

**Comment by mareczek** [comment]
The default options in international-phone-number is set to the same as intlTelInput. Either way, I'll gladly read a pull request

**Comment by mareczek** [comment]
@angrybakon Because I would like to keep things tidy, I'll close this ticket until a pull request arrives. Thank you for taking the time and effort for suggesting features.
