### ISSUE TITLE
Please provide a plnkr with working example

### ISSUE THREAD

**Issue by avi22228** [mareczek/international-phone-number#64]
I am having some issues with binding the input to a model. Please provide a simple plnkr examples so it will be helpful for beginners like me to kick-start.

Thank you ...

**Comment by skfd** [comment]
You can simply open [demo page](http://jackocnr.com/intl-tel-input.html) in dev tools and see how it works.

**Comment by avi22228** [comment]
The demo is written with jQuery, I am looking for a proper angular example.

**Comment by skfd** [comment]
Oh, did not know that. Here's [plunker example](http://plnkr.co/edit/heZxI408fMstMxjkxaMN).

**Comment by avi22228** [comment]
Thanks @skfd , you are awesome. After adding the utils, the binding worked well.

Thanks again, you saved my day.

**Comment by avi22228** [comment]
I removed the validation by using #36 .

Is there a way to return the binding with proper formatting ? I forked your Plunker - http://plnkr.co/edit/1TIsRX?p=info  When I put in a US number, the binding is set to a generic number w/o any formatting. Any way to bind properly formatted number?

**Comment by skfd** [comment]
Here's [my take](http://plnkr.co/edit/DYyfGj?p=preview) on it. I bind to `$viewValue` of input. Not sure why it is empty before touched though. If you find why please write up.

I'm new to angularing, so it might  not be optimal.

**Comment by mareczek** [comment]
@skfd look's like your plunkr works fine with the master branch. Do you think locking the source of international-phone-number wouldn't be safer? For example to the current release 0.0.11

**Comment by skfd** [comment]
Let's make it rolling, I can update it if new version will break it. We can make proper demo to put in readme.

**Comment by mareczek** [comment]
@skfd thank you for the plnkr, I added it to the README.md
