### ISSUE TITLE
Undefined on: element.intlTelInput(options);

### ISSUE THREAD

**Issue by trifroggy** [mareczek/international-phone-number#8]
I am quasi certain that I am the cause of the problem :-)  Yet no matter what I try and setup, I keep on running into undefined is not a function  which points to the line element.intlTelInput(options);
Would you have a basic example that I can work from to see where I am making the mistakes?

thank you!

**Comment by mareczek** [comment]
Try todays' version (16/01/2015). If nothing changes let me know - we'll figure something out.

**Comment by trifroggy** [comment]
Just did. Same result.  I am convinced I am missing something really dumb :)  I can console.log the element , it goes to undefined the moment the intlTelInput is added.

**Comment by Bancalets** [comment]
I was facing the same problem. To fix it, just change the import list order, on your grunt file or equivalent:
        vendor_files: {
            js: [
                'vendor/jquery/dist/jquery.js',
                'vendor/angular/angular.js',
                'vendor/intl-tel-input/build/js/intlTelInput.min.js',
                'vendor/international-phone-number/releases/international-phone-number.js'
                 ...
            ],....

**Comment by trifroggy** [comment]
I'm still out of luck on this one. Starting to wonder if it could also be linked to using ionic/cordova.  I'll use an alternate option for the moment but if you have a basic Plunker to show a setup that works it would be awesome!
Thank you
Gregory

**Comment by trifroggy** [comment]
In case some people happen on this thread, I managed to resolve my issue.  Similar to what Bancalets described except that in my case, I had to put the ionic declaration first, then jquery.
But it's working nicely!

**Comment by atifsaddique211f** [comment]
I had to include all the following dependencies in given order for it to work for me.

`<link rel="stylesheet" href="bower_components/intl-tel-input/build/css/intlTelInput.css">`
  `<script src="bower_components/jquery/dist/jquery.js"></script>`
  `<script src="bower_components/angular/angular.js"></script>`
  `<script src="bower_components/ng-intl-tel-input/dist/ng-intl-tel-input.js"></script>`
  `<script src="bower_components/intl-tel-input/build/js/intlTelInput.js"></script>`
  `<script src="bower_components/intl-tel-input/build/js/utils.js"></script>`
