### ISSUE TITLE
Collaborate with `ng-intl-tel-input` 

### ISSUE THREAD

**Issue by skfd** [mareczek/international-phone-number#80]
Guys from Rackspace did similar wrapper [ng-intl-tel-input](https://github.com/hodgepodgers/ng-intl-tel-input). It's 1.4 only.

Collaborating and broadening the supported versions would be good!

**Comment by mareczek** [comment]
It seems great if it comes to craftsmenship but it's quite poor in terms of config. Another thing is that we purposly reverted the code that made it 1.4 only.

**Comment by skfd** [comment]
Just wanted to point that out and I can't DM you on Github ) Sorry

**Comment by mareczek** [comment]
That's ok, how would you want us to colaborate?
